### ISSUE TITLE
Именования.

### ISSUE THREAD

**Issue by yaroslav-hub** [chkqq/TravelLine#10]
Очень неудачное название проекта, решения и, как следствие, namespace'а.

https://github.com/chkqq/TravelLine/blob/410d902b9cfe8446e0f2a6eb9850ae784c75276d/bb/bb/Program.cs#L7

**Comment by chkqq** [comment]
Понял исправлю

чт, 27 июл. 2023 г., 20:38 Yaroslav ***@***.***>:
