### ISSUE TITLE
Использование переменной.

### ISSUE THREAD

**Issue by yaroslav-hub** [chkqq/TravelLine#11]
Использование переменной не соответствует названию. Перепишите так, чтобы isSorted реально говорил о том, были ли какие-то изменения.

https://github.com/chkqq/TravelLine/blob/410d902b9cfe8446e0f2a6eb9850ae784c75276d/bb/bb/Program.cs#L19

**Comment by chkqq** [comment]
Немного не понял, а это как?

чт, 27 июл. 2023 г., 20:40 Yaroslav ***@***.***>:

**Comment by yaroslav-hub** [comment]
Судя по значениям, которые вы задаёте этой переменной, более подходящее для неё название с отрицанием isNotSorted, однако просто переименовать переменную не получится, т.к. лучше не называть переменные от противного.

**Comment by chkqq** [comment]
Что тогда делать?

вт, 1 авг. 2023 г., 14:17 Yaroslav ***@***.***>:

**Comment by yaroslav-hub** [comment]
Переписать метод.

**Comment by chkqq** [comment]
Изменил переменные и метод

вт, 1 авг. 2023 г., 14:22 Yaroslav ***@***.***>:
