### ISSUE TITLE
Объект string.

### ISSUE THREAD

**Issue by yaroslav-hub** [chkqq/TravelLine#14]
Для чего создаёте новый объект?

https://github.com/chkqq/TravelLine/blob/410d902b9cfe8446e0f2a6eb9850ae784c75276d/bb/bb/Program.cs#L33C45-L33C55

**Comment by chkqq** [comment]
Чтобы превратить массив чар в стринг

чт, 27 июл. 2023 г., 20:43 Yaroslav ***@***.***>:

**Comment by chkqq** [comment]
https://github.com/chkqq/TravelLine/tree/BubbleSort/BubbleSort исправил всё

чт, 27 июл. 2023 г. в 20:45, No Name ***@***.***>:
