### ISSUE TITLE
Проверка работоспособности программы.

### ISSUE THREAD

**Issue by yaroslav-hub** [chkqq/TravelLine#18]
После написания программы необходимо прогнать её хотябы вручную по разным use case. Попробуйте в конструктор треугольника, к примеру, педедать -1, -1, 3.

https://github.com/chkqq/TravelLine/blob/9b38cfefbc6e2c8ca9ab40de6fd7a44f3c5c4020/HomeWork2/HomeWork2/Program.cs#L11

**Comment by chkqq** [comment]
извините, но нам как то про это не говорили, я не знал


чт, 27 июл. 2023 г. в 20:51, Yaroslav ***@***.***>:

**Comment by chkqq** [comment]
ну нам говорили прогнать функции по тестам, я это и сделал


чт, 27 июл. 2023 г. в 21:12, No Name ***@***.***>:

**Comment by chkqq** [comment]
https://github.com/chkqq/TravelLine/tree/BubbleSort/HomeWork2 исправил
ошибку с отрицательными значениями и длиннами треугольников


чт, 27 июл. 2023 г. в 21:14, No Name ***@***.***>:
