### ISSUE TITLE
4 задание

### ISSUE THREAD

**Issue by AlekseiPavlovskii** [chkqq/TravelLine#19]
Не вижу 4 задание (EntityFramework)

**Comment by chkqq** [comment]
https://github.com/chkqq/TravelLine/tree/SqlHomeWork/HomeWork4 извиняюсь
ветки смешались, наверное лучше пересоздать репозиторий

пн, 31 июл. 2023 г., 12:21 AlekseiPavlovskii ***@***.***>:

**Comment by AlekseiPavlovskii** [comment]
Проверил, отписал замечания
