### ISSUE TITLE
Отсутствуют модификаторы доступа

### ISSUE THREAD

**Issue by AlekseiPavlovskii** [chkqq/TravelLine#21]
https://github.com/chkqq/TravelLine/blob/07722a4f733213b31359330163bc4863c37fdcdb/HomeWork4/HomeWork4/Program.cs#L25

**Comment by chkqq** [comment]
А какие тут модификаторы доступа? Public?

пн, 31 июл. 2023 г., 12:31 AlekseiPavlovskii ***@***.***>:

**Comment by AlekseiPavlovskii** [comment]
Лучше private. Эти методы используются только внутри класса

**Comment by chkqq** [comment]
Хорошо, исправлю

пн, 31 июл. 2023 г., 12:44 AlekseiPavlovskii ***@***.***>:
