### ISSUE TITLE
Регулярки.

### ISSUE THREAD

**Issue by yaroslav-hub** [chkqq/TravelLine#6]
Откуда были взяты эти регулярки?

https://github.com/chkqq/TravelLine/blob/ba64999f9adc59dbbd48955d89da3d34331956f7/FIO/FIO/Program.cs#L34

**Comment by chkqq** [comment]
Нашел в интернете (не знал что так нельзя делать)

чт, 27 июл. 2023 г., 15:55 Yaroslav ***@***.***>:

**Comment by yaroslav-hub** [comment]
Делать так можно. Главное, чтобы вы понимали тот код, который используете в готовом виде.

**Comment by chkqq** [comment]
Ну да, я в них разобрался

чт, 27 июл. 2023 г., 20:29 Yaroslav ***@***.***>:
